### ISSUE TITLE
Both verifications (username and password), if active, stop the installation script from working.

### ISSUE THREAD

**Issue by ZDi-it** [ZDi-it/PHPurl#8]
They work if username is too short or passwords don't match, but if both are correct, the script won't proceed to the tables creation.

**Comment by lucasjkr** [comment]
I tested for a couple minutes with what I'd originally submitted and found no reason for it having the issue you were referring to. Then I reviewed your changes, and found the issue:

You commented out line 69 of install.php,, and changed line 72 from:

$stmt -> execute($adminUserValues);

to 

$stmt -> execute($adminName, $adminPW)

That's improper, and prevents the admin name and password from being inserted into the database. Then, when someone tries to create the database again, it will fail because the two tables have already been created.

I'm replacing the install/install.php file - please review.

**Comment by ZDi-it** [comment]
I did it because this is what I'm getting on another test server with PHP Version 5.3.29

![screenshot 1](https://cloud.githubusercontent.com/assets/22733015/20422571/831398a2-ad6b-11e6-9638-bf18bf06614c.png)

I'm noticing now the mistake. Could this fix it?

    $stmt = $pdo->prepare("INSERT INTO admin (username, password) VALUES (:username, :password)");
    $stmt->bindParam(":username", $username);
    $stmt->bindParam(":password", $password);
    $stmt->execute();

**Comment by ZDi-it** [comment]
Merged and changed accordingly. I *still* have issues with two different servers with the checking routines. The header calls are not right for some PHP versions.

**Comment by ZDi-it** [comment]
Through exhaustive inspection I found the culprit:

The new password_* methods are only available as of PHP 5.5:
http://www.php.net/manual/en/function.password-hash.php

It's good if the script uses new technologies, but I can't limit usage either. Salting is the way to go.

**Comment by lucasjkr** [comment]
Respectfully, I give up. PHP 5.3.* is no longer supported by the developers (it stopped receiving security fixes in mid-2014). Even PHP 5.6 (the last of the PHP5 series) is reaching end of life at the end of December. I can't downgrade my staging platform to 5.3, just doesn't make sense to me :)

**Comment by ZDi-it** [comment]
Don't give up :)
The important thing is to set a fixed version to work on as platform.

PHP 5.6 it is!
